version: 2
jobs:
    build:
      docker:
        - image: laht/vcpkg
      steps:
        - checkout
        - run:
            name: Update vcpkg
            command: 'cd /home/vcpkg && git remote add upstream https://github.com/markaren/vcpkg.git && git fetch upstream && git checkout upstream/update/fmi4cpp'
        - run:
            name: Install dependencies
            command: 'cd /home/vcpkg && ./vcpkg upgrade --no-dry-run && ./vcpkg install fmi4cpp --recurse'
        - run:
            name: Configuring
            command: 'cmake -H. -Bbuild -DCMAKE_TOOLCHAIN_FILE=/home/vcpkg/scripts/buildsystems/vcpkg.cmake'
        - run:
            name: Building
            command: 'cmake --build build'
        - run:
            name: Unit tests
            command: 'cd build/bin && ctest'
